export const ADD_CIRCLE = "ADD_CIRCLE"
export const LOADING_CIRCLES = "LOADING_CIRCLES"
export const LOADED_CIRCLES = "LOADED_CIRCLES"
export const LOADING_CIRCLE = "LOADING_CIRCLE"
export const LOADED_CIRCLE = "LOADED_CIRCLE"
export const LOADING_FAILED = "LOADING_FAILED"

export const UPDATE_CIRCLE = "UPDATE_CIRCLE"

export const LOADING_CIRCLE_POSTS = "LOADING_CIRCLE_POSTS"
export const LOADED_CIRCLE_POSTS = "LOADED_CIRCLE_POSTS"


export const CREATED_CIRCLE = "CREATED_CIRCLE"
export const ERROR_CREATING_CIRCLE = "ERROR_CREATING_CIRCLE"

export const CREATED_POST = "CREATED_POST"
